force-app/main/default/objects/FieldRollup__c/FieldRollup__c.object-meta.xml
<CustomObject>
    <label>Field Rollup</label>
    <nameField>
        <label>Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field Rollups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FieldRollup__c/fields/ChildObjectName__c.field-meta.xml
<CustomField>
    <fullName>ChildObjectName__c</fullName>
    <label>Child Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieldRollup__c/fields/ChildRelationshipName__c.field-meta.xml
<CustomField>
    <fullName>ChildRelationshipName__c</fullName>
    <label>Child Relationship Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieldRollup__c/fields/ParentObjectName__c.field-meta.xml
<CustomField>
    <fullName>ParentObjectName__c</fullName>
    <label>Parent Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieldRollup__c/fields/RollupFieldName__c.field-meta.xml
<CustomField>
    <fullName>RollupFieldName__c</fullName>
    <label>Rollup Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FieldRollup__c/fields/RollupType__c.field-meta.xml
<CustomField>
    <fullName>RollupType__c</fullName>
    <label>Rollup Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COUNT</fullName>
            </value>
            <value>
                <fullName>SUM</fullName>
            </value>
            <value>
                <fullName>MAX</fullName>
            </value>
            <value>
                <fullName>MIN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/data/FieldRollupData.cls
public inherited sharing class FieldRollupData {
    
    private static final List<String> FIELDS = new List<String>{
        'Id', 'Name', 'ParentObjectName__c', 'ChildObjectName__c',
        'ChildRelationshipName__c', 'RollupFieldName__c', 'RollupType__c'
    };

    public static List<FieldRollup__c> getFieldRollupsByParentObject(String objectName) {
        String query = 'SELECT ' + String.join(FIELDS, ', ') + ' FROM FieldRollup__c';
        query += ' WHERE ParentObjectName__c = :objectName';
        return (List<FieldRollup__c>) Database.query(query);
    }
}